-----------------------------------------------------
--name       : template.lua
--description: a template header for all files
--author     : mpmxyz
--github page: https://github.com/mpmxyz/ocprograms
--forum page : http://oc.cil.li/index.php?/topic/
-----------------------------------------------------
